language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get install -y
      automake
      autoconf
      autoconf-archive
      libtool
      liblz4-dev
      liblzma-dev
      make
      zlib1g-dev
      binutils-dev
      libjemalloc-dev
      libiberty-dev
      libjsoncpp-dev
  - sudo sh get_boost.sh

script: autoreconf -ivf && ./configure && make -j4
